name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: untitaker/hyperlink@0.1.21
      with:
        args: /blog /community /docs /download /faq /i18n /versioned_docs
