name: Check Markdown links

on: push

jobs:
  validate_links:
    name: Markdown links verifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Validate links
      uses: Youssef1313/markdown-links-verifier@v0.1.3
      with:
        args: --config-file /home/runner/work/incubator-linkis-website/incubator-linkis-website/.github/workflows/check.json
